# Generated by Django 2.1.7 on 2020-02-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_movie_scores',
            fields=[
                ('movie_score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=80)),
                ('cinematography', models.CharField(max_length=80)),
                ('story_telling', models.CharField(max_length=80)),
                ('acting', models.CharField(max_length=80)),
                ('plausibility', models.CharField(max_length=80)),
                ('cast', models.CharField(max_length=80)),
                ('effects', models.CharField(max_length=80)),
                ('fun_factor', models.CharField(max_length=80)),
                ('originality', models.CharField(max_length=80)),
                ('characters', models.CharField(max_length=80)),
                ('total', models.CharField(max_length=80)),
                ('review', models.CharField(max_length=4000)),
                ('user_id', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=80)),
                ('movie_genre', models.CharField(max_length=80)),
                ('movie_release_year', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_movie_scores',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tbl_movies'),
        ),
    ]
