# Generated by Django 3.0.3 on 2020-02-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200226_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie_scores',
            name='movie_score_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_movies',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
