# Generated by Django 3.0.3 on 2020-03-14 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200301_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie_scores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_movie_scores',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
