# Generated by Django 3.0.3 on 2020-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200314_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie_scores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_movie_scores',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
