# Generated by Django 3.0.3 on 2020-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200315_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movies',
            name='movie_poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
