# Generated by Django 3.0.3 on 2020-03-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tbl_movies_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_movie_scores',
            name='movie',
        ),
        migrations.AddField(
            model_name='tbl_movie_scores',
            name='movie_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
