# Generated by Django 3.0.3 on 2020-03-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200329_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie_scores',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
