# Generated by Django 3.0.3 on 2020-04-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200330_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie_scores',
            name='movie_id',
            field=models.CharField(max_length=40),
        ),
    ]
