# Generated by Django 3.0.3 on 2020-04-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200401_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_movie_scores',
            name='movie_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
