# Generated by Django 3.0.3 on 2020-04-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200401_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_movie_scores',
            old_name='score',
            new_name='sound',
        ),
    ]
