# Generated by Django 3.0.3 on 2020-04-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200423_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_catagory_desc',
            old_name='acting',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='cinematography',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='fun_factor',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='originality',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='plausibility',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='tbl_catagory_desc',
            name='story_telling',
        ),
        migrations.AddField(
            model_name='tbl_catagory_desc',
            name='catagory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
