# Generated by Django 3.0.3 on 2020-04-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200423_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_catagory_desc',
            new_name='tbl_category_desc',
        ),
        migrations.RenameField(
            model_name='tbl_category_desc',
            old_name='catagory',
            new_name='category',
        ),
    ]
