# Generated by Django 3.0.3 on 2020-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200424_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_movie_scores',
            name='poster',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
