# Generated by Django 3.0.3 on 2020-06-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tbl_user_last_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user_last_search',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
