# Generated by Django 3.0.3 on 2020-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_tbl_user_last_search_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user_last_search',
            name='user',
        ),
        migrations.AddField(
            model_name='tbl_user_last_search',
            name='session_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
